---
- name: Redis yum 저장소 추가
  yum_repository:
    name: remi-redis
    description: Remi Redis repository
    baseurl: "http://rpms.remirepo.net/enterprise/{{ ansible_distribution_major_version }}/redis{{ redis_version | replace('.', '') }}/$basearch/"
    gpgcheck: false
    enabled: true
  when: ansible_os_family == "RedHat"

- name: Redis 패키지 설치
  package:
    name:
      - redis
    state: present

- name: Redis 데이터 디렉토리 생성
  file:
    path: "{{ redis_dir }}"
    state: directory
    owner: redis
    group: redis
    mode: "0750"

- name: Redis 로그 디렉토리 생성
  file:
    path: "/var/log/redis"
    state: directory
    owner: redis
    group: redis
    mode: "0750"

- name: Redis 서비스 활성화 및 시작
  service:
    name: redis
    state: started
    enabled: true
